module Peripherals

include("peripherals/xip_ctrl.jl")
include("peripherals/xip_ssi.jl")
include("peripherals/sysinfo.jl")
include("peripherals/syscfg.jl")
include("peripherals/clocks.jl")
include("peripherals/resets.jl")
include("peripherals/psm.jl")
include("peripherals/io_bank0.jl")
include("peripherals/io_qspi.jl")
include("peripherals/pads_bank0.jl")
include("peripherals/pads_qspi.jl")
include("peripherals/xosc.jl")
include("peripherals/pll_sys.jl")
include("peripherals/pll_usb.jl")
include("peripherals/busctrl.jl")
include("peripherals/uart0.jl")
include("peripherals/uart1.jl")
include("peripherals/spi0.jl")
include("peripherals/spi1.jl")
include("peripherals/i2c0.jl")
include("peripherals/i2c1.jl")
include("peripherals/adc.jl")
include("peripherals/pwm.jl")
include("peripherals/timer.jl")
include("peripherals/watchdog.jl")
include("peripherals/rtc.jl")
include("peripherals/rosc.jl")
include("peripherals/vreg_and_chip_reset.jl")
include("peripherals/tbman.jl")
include("peripherals/dma.jl")
include("peripherals/usbctrl_dpram.jl")
include("peripherals/usbctrl_regs.jl")
include("peripherals/pio0.jl")
include("peripherals/pio1.jl")
include("peripherals/sio.jl")
include("peripherals/ppb.jl")

end # module
